import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { GerritReviewSink } from "../src/report/sinks/gerrit.js";
import { makeFinding, type Finding } from "../src/report/finding.js";

function f(file: string, line: number, severity: any, category: any, title = "x"): Finding {
  return makeFinding(
    {
      file,
      line,
      severity,
      title,
      rationale: "r",
      suggestion: "",
      confidence: 0.9,
      evidence: [],
    },
    category,
  );
}

interface FakeCall {
  url: string;
  method: string;
  body: any;
  authHeader?: string;
}

let calls: FakeCall[];

beforeEach(() => {
  calls = [];
  vi.spyOn(globalThis, "fetch").mockImplementation(async (url: any, init: any) => {
    const auth = (init?.headers as any)?.Authorization;
    calls.push({
      url: String(url),
      method: (init?.method ?? "GET").toUpperCase(),
      body: init?.body ? JSON.parse(String(init.body)) : undefined,
      authHeader: auth,
    });
    // Gerrit responses begin with the magic `)]}'` prefix.
    return new Response(")]}'\n{}", { status: 200 });
  });
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe("GerritReviewSink", () => {
  it("posts a review with file-grouped inline comments + summary message", async () => {
    const sink = new GerritReviewSink({
      baseUrl: "https://gerrit.example.com",
      changeId: 12345,
      revision: "current",
      user: "alice",
      password: "pw",
    });
    const findings = [
      f("src/a.cpp", 10, "high", "concurrency", "race"),
      f("src/a.cpp", 22, "low", "maintainability", "minor"),
      f("src/b.cpp", 5, "critical", "memory", "leak"),
    ];
    const res = await sink.post(findings, { commit: null });

    expect(res.inlineComments).toBe(3);
    expect(res.summaryPosted).toBe(true);

    const call = calls[0];
    expect(call.method).toBe("POST");
    expect(call.url).toContain("/a/changes/12345/revisions/current/review");
    expect(call.authHeader).toMatch(/^Basic /);
    // base64('alice:pw')
    expect(call.authHeader).toBe(`Basic ${Buffer.from("alice:pw").toString("base64")}`);
    expect(call.body.tag).toBe("autogenerated:reviewforge");
    expect(call.body.message).toMatch(/3 finding/);
    expect(Object.keys(call.body.comments).sort()).toEqual(["src/a.cpp", "src/b.cpp"]);
    expect(call.body.comments["src/a.cpp"]).toHaveLength(2);
    // critical/high severities mark the comment unresolved.
    const critComment = call.body.comments["src/b.cpp"][0];
    expect(critComment.unresolved).toBe(true);
    const lowComment = call.body.comments["src/a.cpp"].find((c: any) => c.line === 22);
    expect(lowComment.unresolved).toBe(false);
  });

  it("strips the )]}' prefix from Gerrit responses without throwing", async () => {
    const sink = new GerritReviewSink({
      baseUrl: "https://gerrit.example.com/",
      changeId: 1,
      revision: "current",
      user: "u",
      password: "p",
    });
    await expect(sink.post([], { commit: null })).resolves.toBeDefined();
  });
});
