import { fetchWithRetry } from "../../providers/http.js";
import { SEVERITIES, severityRank, type Finding, type Severity } from "../finding.js";
import { type PostResult, type ReviewSink, ReviewSinkError, type SinkContext } from "./types.js";

export interface GerritSinkConfig {
  /** Base URL, e.g. https://gerrit.example.com */
  baseUrl: string;
  /** Change number or Change-Id. */
  changeId: string | number;
  /** Revision to attach comments to (defaults to "current"). */
  revision: string;
  /** HTTP basic auth: user (often the username with HTTP password). */
  user: string;
  password: string;
}

const SEV_LABEL: Record<Severity, string> = {
  critical: "CRITICAL",
  high: "HIGH",
  medium: "MEDIUM",
  low: "LOW",
};

function inlineComment(f: Finding): string {
  const parts: string[] = [];
  parts.push(`[${SEV_LABEL[f.severity]} · ${f.category} · conf=${(f.confidence * 100).toFixed(0)}%]`);
  parts.push(f.title);
  parts.push("");
  parts.push(f.rationale);
  if (f.suggestion) {
    parts.push("");
    parts.push(`Suggestion: ${f.suggestion}`);
  }
  if (f.suggestedPatch) {
    parts.push("");
    parts.push("Suggested replacement:");
    parts.push(f.suggestedPatch);
  }
  if (f.evidence.length) {
    parts.push("");
    parts.push("Evidence:");
    for (const e of f.evidence) parts.push(`  - ${e.type}: ${e.ref}`);
  }
  parts.push("");
  parts.push(`-- ReviewForge (id ${f.id})`);
  return parts.join("\n");
}

function reviewMessage(findings: Finding[]): string {
  const counts: Record<string, number> = {};
  for (const s of SEVERITIES) counts[s] = 0;
  for (const f of findings) counts[f.severity]++;
  if (findings.length === 0) {
    return "ReviewForge: no findings above the configured threshold.";
  }
  const tally = SEVERITIES.map((s) => `${s}: ${counts[s]}`).join(" · ");
  return `ReviewForge — ${findings.length} finding(s) (${tally}). See inline comments.`;
}

/**
 * Gerrit REST API uses the magic prefix `)]}'` before JSON responses; we strip it.
 */
async function gerritFetch(
  cfg: GerritSinkConfig,
  method: string,
  path: string,
  body?: unknown,
): Promise<any> {
  const url = `${cfg.baseUrl.replace(/\/$/, "")}/a${path}`;
  const auth = Buffer.from(`${cfg.user}:${cfg.password}`).toString("base64");
  const res = await fetchWithRetry(
    url,
    {
      method,
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: `Basic ${auth}`,
      },
      body: body ? JSON.stringify(body) : undefined,
    },
    { timeoutMs: 60_000, retries: 3 },
  );
  const text = await res.text();
  if (!res.ok) {
    throw new ReviewSinkError(`Gerrit ${method} ${path} -> ${res.status}: ${text.slice(0, 300)}`);
  }
  const stripped = text.startsWith(")]}'") ? text.slice(4).trimStart() : text;
  return stripped ? JSON.parse(stripped) : {};
}

export class GerritReviewSink implements ReviewSink {
  readonly name = "gerrit";
  constructor(private readonly cfg: GerritSinkConfig) {}

  buildPayload(findings: Finding[]): {
    endpoint: string;
    method: "POST";
    body: unknown;
  } {
    const comments: Record<string, { line: number; message: string; unresolved?: boolean }[]> = {};
    for (const f of findings) {
      (comments[f.file] ??= []).push({
        line: Math.max(1, f.line),
        message: inlineComment(f),
        unresolved: severityRank(f.severity) <= severityRank("high"),
      });
    }
    return {
      method: "POST",
      endpoint: `/changes/${encodeURIComponent(String(this.cfg.changeId))}/revisions/${encodeURIComponent(
        this.cfg.revision,
      )}/review`,
      body: {
        message: reviewMessage(findings),
        comments,
        tag: "autogenerated:reviewforge",
      },
    };
  }

  async post(findings: Finding[], ctx: SinkContext): Promise<PostResult> {
    const log = ctx.log ?? (() => {});
    const payload = this.buildPayload(findings);
    const inlineCount = Object.values(
      (payload.body as any).comments as Record<string, unknown[]>,
    ).reduce((acc, arr) => acc + arr.length, 0);

    if (ctx.dryRun) {
      log(`[dry-run] Would ${payload.method} ${payload.endpoint}`);
      log(`[dry-run] Payload preview: ${JSON.stringify(payload.body).slice(0, 200)}...`);
      return {
        inlineComments: inlineCount,
        summaryPosted: true,
        refs: [`dry-run://gerrit${payload.endpoint}`],
        warnings: [],
      };
    }

    await gerritFetch(this.cfg, "POST", payload.endpoint, payload.body);
    log(`Posted Gerrit review with ${inlineCount} inline comment(s).`);
    return {
      inlineComments: inlineCount,
      summaryPosted: true,
      refs: [`${this.cfg.baseUrl}/c/+/${this.cfg.changeId}`],
      warnings: [],
    };
  }
}
